---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: workloaddescriptors.kompass.zesty.co
spec:
  group: kompass.zesty.co
  names:
    kind: WorkloadDescriptor
    listKind: WorkloadDescriptorList
    plural: workloaddescriptors
    singular: workloaddescriptor
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.protection.state
      name: State
      type: string
    - jsonPath: .status.protection.lastUpdatedAt
      name: Last_Updated
      type: date
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: WorkloadDescriptor is the entity responsible for protecting user
          selected workload
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              draining:
                default: {}
                description: The configuration for how to drain pods from the workload
                properties:
                  method:
                    default: accelerated
                    description: The method used for draining pods.
                    enum:
                    - accelerated
                    - regular
                    type: string
                  threshold:
                    anyOf:
                    - type: integer
                    - type: string
                    default: 10%
                    description: The percentage of pods in the workload that can be
                      unavailable during the drain operation.
                    pattern: ^(100|[0-9]{1,2})%?$
                    x-kubernetes-int-or-string: true
                type: object
              protection:
                description: The configuration for how to protect the workload
                properties:
                  resources:
                    description: |-
                      Resources needed to protect the Workload
                      Kompass chooses the number of hibernated nodes based on the total resources across all WorkloadDescriptors
                    properties:
                      cpu:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      memory:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                    required:
                    - cpu
                    - memory
                    type: object
                  spike:
                    default: {}
                    description: Spike protection configuration
                    properties:
                      active:
                        default: false
                        description: Should Hibernated nodes be resumed when the workload
                          is in a spike?
                        type: boolean
                      strategy:
                        default: manual
                        description: |-
                          The strategy for calculating the minReplicas for the HPA.
                          Strategy of type "manual" means that Kompass will not automatically calculate set minReplicas for the HPA.
                          "default" means that Kompass will automatically calculate the minReplicas for the HPA.
                          "conservative" is similar to default but is more focused on availability and sets a higher value of minReplica.
                        enum:
                        - manual
                        - default
                        - conservative
                        type: string
                      threshold:
                        anyOf:
                        - type: integer
                        - type: string
                        default: 20%
                        description: |-
                          The percentage of pods in the workload that should be Unschedulable to trigger resumption of hibernated nodes.
                          The threshold is needed, to prevent unnecessary resumption of hibernated nodes.
                        pattern: ^(100|[0-9]{1,2})%?$
                        x-kubernetes-int-or-string: true
                    type: object
                  spot:
                    default: {}
                    description: Spot protection configuration
                    properties:
                      active:
                        default: false
                        description: Should Hibernated nodes be resumed when a node
                          that hosts a pod of the workload receives a spot termination
                          notice?
                        type: boolean
                      strategy:
                        default: manual
                        description: For future use
                        enum:
                        - manual
                        - default
                        - conservative
                        type: string
                    type: object
                required:
                - resources
                type: object
              workloadReference:
                description: |-
                  A reference the workload that is being protected by this WorkloadDescriptor object.
                  The workload must be in the same namespace as the WorkloadDescriptor object.
                properties:
                  apiVersion:
                    description: 'For example: apps/v1'
                    type: string
                  kind:
                    description: 'For example: Deployment'
                    type: string
                  name:
                    description: The name of the workload to reference
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
            required:
            - workloadReference
            type: object
          status:
            properties:
              draining:
                properties:
                  lastUpdatedAt:
                    description: The last time the status for Draining configuration
                      was updated.
                    format: date-time
                    type: string
                  maxUnavailableDuringDrain:
                    description: Maximum number of pods that can be unavailable during
                      the drain operation.
                    format: int32
                    type: integer
                required:
                - lastUpdatedAt
                - maxUnavailableDuringDrain
                type: object
              hpa:
                properties:
                  lastUpdatedAt:
                    description: The last time the status for HPA configuration was
                      updated.
                    format: date-time
                    type: string
                  minReplicas:
                    description: The MinReplicas that the HPA should be configured
                      with.
                    format: int32
                    type: integer
                required:
                - lastUpdatedAt
                type: object
              protection:
                properties:
                  lastUpdatedAt:
                    description: LastUpdatedAt
                    format: date-time
                    type: string
                  message:
                    description: Message
                    type: string
                  minUnavailableForResumption:
                    description: Minimum number of pods that should not be available
                      to trigger
                    format: int32
                    type: integer
                  protectingQScalers:
                    description: How to distribute the resources across all QScalers
                    items:
                      properties:
                        name:
                          description: Name
                          type: string
                        resources:
                          description: Resources allocated to the QScaler to protect
                            the Workload
                          properties:
                            cpu:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            memory:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            minimumQNodes:
                              format: int32
                              type: integer
                          required:
                          - cpu
                          - memory
                          - minimumQNodes
                          type: object
                      required:
                      - name
                      - resources
                      type: object
                    type: array
                  state:
                    description: State
                    enum:
                    - Active
                    - Pending
                    - Failed
                    type: string
                required:
                - lastUpdatedAt
                - minUnavailableForResumption
                type: object
            type: object
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
