---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: qbakers.qscaler.qubex.ai
spec:
  group: qscaler.qubex.ai
  names:
    kind: QBaker
    listKind: QBakerList
    plural: qbakers
    singular: qbaker
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.qNodeStatuses[?(@.phase == 'Hibernated')].count
      name: Hibernated
      type: integer
    - jsonPath: .status.qNodeStatuses[?(@.phase == 'Running')].count
      name: Running
      type: integer
    - jsonPath: .status.currentCapacity
      name: Current_Capacity
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: QBaker is the entity responsible for ensuring that there is always
          a sufficiently large pool of hibernated QNodes.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              aws:
                description: The AWS specific configuration for the node
                properties:
                  AMIs:
                    description: AMI details for the underlying VMs
                    items:
                      properties:
                        architecture:
                          description: Architecture of the AMI
                          enum:
                          - AMD64
                          - ARM64
                          type: string
                        deviceMappings:
                          additionalProperties:
                            properties:
                              deviceName:
                                type: string
                              sizeGB:
                                format: int32
                                type: integer
                              type:
                                type: string
                            type: object
                          description: The device mapping entries associated with
                            this target
                          type: object
                        imageID:
                          description: The AWS AIM ID to be used for the underlying
                            VMs
                          type: string
                        rootVolumeName:
                          description: The AWS root volume name to be applied to the
                            underlying VM
                          type: string
                      type: object
                    type: array
                  allowPublicIP:
                    description: Whether to allow public IPs for the underlying VMs
                    type: boolean
                  imdsMaxHopCount:
                    description: Imds max hop count
                    format: int32
                    type: integer
                  imdsVersion:
                    description: Imds version
                    type: string
                  instanceProfileArn:
                    description: Instance profile arn
                    type: string
                  securityGroupIds:
                    description: The security groups to be applied to the underlying
                      VM
                    items:
                      type: string
                    type: array
                  zoneDetails:
                    additionalProperties:
                      properties:
                        subnetIds:
                          description: The subnet id that will be used for the QNodes
                            in the zone
                          items:
                            type: string
                          type: array
                      type: object
                    description: A map containing zone specific details for all zones
                      covered by the QScaler
                    type: object
                type: object
              instanceTypeConfigurations:
                description: The instance type configurations for the baker
                items:
                  properties:
                    desiredNodeCount:
                      description: The desired nodes the baker should bake
                      format: int32
                      type: integer
                    instanceType:
                      description: The instance type in the corresponding cloud provider
                      type: string
                  required:
                  - desiredNodeCount
                  - instanceType
                  type: object
                type: array
              labels:
                additionalProperties:
                  maxLength: 63
                  type: string
                description: The node labels to be applied to the node
                type: object
              taints:
                description: The node taints to be applied to the node
                items:
                  description: |-
                    The node this Taint is attached to has the "effect" on
                    any pod that does not tolerate the Taint.
                  properties:
                    effect:
                      description: |-
                        Required. The effect of the taint on pods
                        that do not tolerate the taint.
                        Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
                      type: string
                    key:
                      description: Required. The taint key to be applied to a node.
                      type: string
                    timeAdded:
                      description: |-
                        TimeAdded represents the time at which the taint was added.
                        It is only written for NoExecute taints.
                      format: date-time
                      type: string
                    value:
                      description: The taint value corresponding to the taint key.
                      type: string
                  required:
                  - effect
                  - key
                  type: object
                type: array
              target:
                description: The target to which QNodes should be added
                properties:
                  castAINodeTemplateTarget:
                    description: Reference for the nodegroup if it's of type CastAINodeTemplate
                    properties:
                      nodeTemplateName:
                        description: The name of the node template to be shadowed
                        type: string
                    required:
                    - nodeTemplateName
                    type: object
                  clusterAutoscalerTarget:
                    description: Reference for the nodegroup if it's of type ClusterAutoscalerASG
                    properties:
                      asgName:
                        description: The name of the ASG to be shadowed
                        type: string
                    required:
                    - asgName
                    type: object
                  karpenterB1Target:
                    description: Reference for the nodegroup if it's of type KarpenterB1Target
                    properties:
                      nodePoolName:
                        description: The name of the nodepool to be shadowed
                        type: string
                    required:
                    - nodePoolName
                    type: object
                  karpenterV1Target:
                    description: Reference for the nodegroup if it's of type KarpenterV1Target
                    properties:
                      nodePoolName:
                        description: The name of the nodepool to be shadowed
                        type: string
                    required:
                    - nodePoolName
                    type: object
                  nodegroupName:
                    description: Nodegroup name
                    type: string
                  spotVNGTarget:
                    description: Reference for the nodegroup if it's of type SpotVNGTarget
                    properties:
                      launchSpecID:
                        description: The launch spec ID
                        type: string
                      oceanId:
                        description: The ocean ID
                        type: string
                    required:
                    - launchSpecID
                    - oceanId
                    type: object
                  staticTarget:
                    description: Reference for the nodegroup if it's of type StaticNodegroup
                    properties:
                      awsNodeGroupParams:
                        description: |-
                          A little bit of a hack: a static target means we configure everything manually
                          so, copy the Infra params and node params to the qscaler params
                        properties:
                          AMIs:
                            description: AMI details for the underlying VMs
                            items:
                              properties:
                                architecture:
                                  description: Architecture of the AMI
                                  enum:
                                  - AMD64
                                  - ARM64
                                  type: string
                                deviceMappings:
                                  additionalProperties:
                                    properties:
                                      deviceName:
                                        type: string
                                      sizeGB:
                                        format: int32
                                        type: integer
                                      type:
                                        type: string
                                    type: object
                                  description: The device mapping entries associated
                                    with this target
                                  type: object
                                imageID:
                                  description: The AWS AIM ID to be used for the underlying
                                    VMs
                                  type: string
                                rootVolumeName:
                                  description: The AWS root volume name to be applied
                                    to the underlying VM
                                  type: string
                              type: object
                            type: array
                          allowPublicIP:
                            description: |-
                              Whether to add a public IP to the network interface of the underlying VM
                              The field will be passed as is to the associatePublicIpAddress parameter of the AWS API
                              nil value means that the default value of the AWS API will be used
                            type: boolean
                          allowedInstanceTypes:
                            description: The AWS instance types that are allowed by
                              the upstream nodepool definition
                            items:
                              type: string
                            type: array
                          availabilityZones:
                            description: The availability zones associated with this
                              target
                            items:
                              type: string
                            type: array
                          iamInstanceProfileArn:
                            description: The IAM instance profile to be used for the
                              underlying VMs
                            type: string
                          imdsMaxHopCount:
                            description: The IMDS max hop count to be used for the
                              underlying VMs
                            format: int32
                            type: integer
                          imdsVersion:
                            description: The IMDS version to be used for the underlying
                              VMs
                            type: string
                          securityGroupIds:
                            description: The security groups associated with this
                              target
                            items:
                              type: string
                            type: array
                          subnets:
                            description: |-
                              The AWS key pair to be used for the underlying VMs
                              The tags associated with this target
                              TemplateTags     map[string]string `json:"templateTags,omitempty"`
                              The active AWS subnets for this target
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  type:
                    description: The type of the target
                    enum:
                    - ClusterAutoscalerASG
                    - KarpenterNodepoolB1
                    - KarpenterNodepoolV1
                    - SpotVNG
                    - StaticNodegroup
                    - CastAINodeTemplate
                    type: string
                  upstreamCloudName:
                    description: Upstream cloud name
                    type: string
                required:
                - type
                type: object
            required:
            - target
            type: object
          status:
            properties:
              currentCapacity:
                description: The current number of hibernated and preparing QNodes
                format: int32
                type: integer
              qNodeStatuses:
                description: Number of QNodes per phase
                items:
                  properties:
                    count:
                      type: integer
                    phase:
                      enum:
                      - Initializing
                      - OnHold
                      - Baking
                      - RequestingHibernation
                      - Hibernating
                      - Hibernated
                      - RequestingResume
                      - Resuming
                      - Running
                      - RequiresUpdate
                      - RequestingCacheUpdate
                      - UpdatingCache
                      - Draining
                      - Terminating
                      type: string
                  required:
                  - count
                  - phase
                  type: object
                type: array
              resumeQueueUrls:
                description: internal usage - the sqs queue from which the QNode will
                  receive messages about resume/abort
                items:
                  properties:
                    queueUrl:
                      description: The URL of the SQS queue from which the QNode will
                        receive messages about resume/abort
                      type: string
                    shardId:
                      description: the related shard identifier
                      type: string
                  required:
                  - queueUrl
                  - shardId
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
