{{- if and .Values.secretValidator.enabled .Values.secretValidator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kompass-compute.secretValidator.serviceAccountName" . }}
  labels:
    {{- include "kompass-compute.secretValidator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.secretValidator.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.secretValidator.serviceAccount.automount }}
{{- end }}