{{- if and .Values.secretValidator.enabled .Values.secretValidator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kompass-compute.secretValidator.name" . }}
  labels:
    {{- include "kompass-compute.secretValidator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kompass-compute.secretValidator.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kompass-compute.secretValidator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
