{{- if and .Values.secretValidator.enabled .Values.secretValidator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kompass-compute.secretValidator.name" . }}
  labels:
    {{- include "kompass-compute.secretValidator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ include "kompass-compute.insightSecretName" . | quote }}]
    verbs: ["get"]
{{- end }}    